### ISSUE TITLE
How to play a short term forecasting experiment with exchange_rate dataset?

### ISSUE THREAD

**Issue by wbzhang233** [aikunyi/FilterNet#4]
I want to make a experiment with exchange_rate dataset, I downloaded the dataset and set my custom arguments, including modefied the `run.py` file. I failed, cause' there some probelms with the data_provider and data_loader, shall I change the `data` argument to 'custom'? I don't know how to train and predict with exchange_rate dataset.

---

请问怎么用外汇数据集进行短期的训练和预测啊？我修改了run.py里面Exp那行，然后修改了输入参数，但是我发现你们的data_provider模块中代码还不完善，提示报错，就是不知道怎么设置取数模块，我猜测是不是除了ETT数据集你们都用那个custom data_loader?

**Comment by wbzhang233** [comment]
```shell
model_name=PaiFilter

python -u run.py \
  --task_name short_term_forecast \
  --is_training 1 \
  --root_path ../dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id exchange_rate_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --enc_in 7 \
  --seq_len 96 \
  --label_len 96 \
  --pred_len 96 \
  --hidden_size 256 \
  --train_epochs 15 \
  --batch_size 32 \
  --patience 5 \
  --learning_rate 0.01 \
  --des 'Exp' \
  --itr 1
```
我写的.sh文件像上面这样，但是报了个这个错。
```shell
>>>>>>>start training : exchange_rate_96_96_PaiFilter_custom_sl96_pl96_embed128_hidden256_bs32_lr0.01_drop0_0>>>
>>>>>>>>>>>>>>>>>>>>>>>
train 5120
val 665
Traceback (most recent call last):
  File "D:\Code\InsightMacro\models\FilterNet\run.py", line 130, in <module>
    exp.train(setting)
  File "D:\Code\InsightMacro\models\FilterNet\exp\exp_short_term_forecasting.py", line 88, in train
    outputs = self.model(batch_x, None, dec_inp, None)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\fomcts\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapp
ed_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\fomcts\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_
impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\InsightMacro\models\FilterNet\models\PaiFilter.py", line 35, in forward
    z = self.revin_layer(z, 'norm')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\fomcts\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapp
ed_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\fomcts\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_
impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Code\InsightMacro\models\FilterNet\layers\RevIN.py", line 22, in forward
    x = self._normalize(x)
        ^^^^^^^^^^^^^^^^^^
  File "D:\Code\InsightMacro\models\FilterNet\layers\RevIN.py", line 48, in _normalize
    x = x * self.affine_weight
        ~~^~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (8) must match the size of tensor b (7) at non-singleton dimension 2
```

**Comment by TaySwiftieTay** [comment]
It’s not that the code in the data_provider module is incomplete; it’s your parameter settings that are incorrect. For the exchange_rate dataset, please set enc_in to 8, as the exchange_rate dataset has 8 variables.

**Comment by wbzhang233** [comment]
> It’s not that the code in the data_provider module is incomplete; it’s your parameter settings that are incorrect. For the exchange_rate dataset, please set enc_in to 8, as the exchange_rate dataset has 8 variables.

Thanks for you reply, I have found this problem yesterday. I have succeed to made a experiment with exchange_rate of long term forecasting, and I wonder why use the function `time_features` to encoding `date` columns of date, I mean that we cannot get the original timestamp from the encoded time stamp cause's all the encoding was relative, such as DayOfWeek, WeekOfMonth, MonthOfYear. I don't know why use this method to encode timestamp.
BTW. Is there any other method to predict with thie model but using `test` that set the param `is_traing` equal 0.
Thanks. ❤

**Comment by wbzhang233** [comment]
Additional. I have wrote a `predict` function for long term forecasting. But I don't know how to run a short term forecasting experiment with DataSet_M4, debugging is too bothering to do, so hoping for your generous opening of more complete source code. Thanks. 💚

**Comment by wbzhang233** [comment]
How to make short term forecasting experiment? Big probelm jesz
